[workspace]
members = ["crates/*", "support/forja-testing", "support/test-guests"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
rust-version = "1.98.1"
version = "0.0.0"

[workspace.dependencies]
wasmtime = { version = "49", default-features = false, features = [
  "component-model",
  "cranelift",
  "runtime",
] }
wasmtime-wasi = { version = "49", default-features = false, features = ["p2"] }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
