[package]
name = "test-guests"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[build-dependencies]
forja-build = { path = "../../crates/forja-build" }
forja-config = { path = "../../crates/forja-config" }
toml.workspace = true

[dev-dependencies]
wasmtime.workspace = true
wasmtime-wasi.workspace = true

[lints]
workspace = true
