use forja_core::program::{BinOp, Inst, Program, ProgramKind, RedOp, UnOp, ValueType};

pub fn context_program() -> Program {
    Program {
        kind: ProgramKind::Row,
        insts: vec![
            Inst::Input(0),
            Inst::Input(1),
            Inst::Const(0.5),
            Inst::Index(0),
            Inst::Extent(0),
            Inst::Unary(UnOp::Floor, 0),
            Inst::Binary(BinOp::Mul, 0, 2),
            Inst::Binary(BinOp::Max, 1, 3),
            Inst::Binary(BinOp::Le, 0, 2),
            Inst::Select(8, 5, 6),
            Inst::Cast(ValueType::F32, 7),
            Inst::Reduce(RedOp::Max, 9),
            Inst::Binary(BinOp::Add, 9, 11),
            Inst::Reduce(RedOp::Min, 12),
            Inst::Reduce(RedOp::Max, 10),
            Inst::Binary(BinOp::Gt, 10, 12),
            Inst::Binary(BinOp::Max, 12, 11),
            Inst::Unary(UnOp::Neg, 2),
            Inst::Const(-21.75),
            Inst::Unary(UnOp::Sigmoid, 2),
            Inst::Const(21.75),
            Inst::Input(1),
            Inst::Input(1),
            Inst::Input(1),
            Inst::Input(1),
            Inst::Extent(0),
            Inst::Binary(BinOp::Sub, 6, 13),
            Inst::Input(0),
            Inst::Input(0),
            Inst::Select(8, 5, 19),
            Inst::Const(29.25),
            Inst::Binary(BinOp::Mul, 23, 1),
            Inst::Binary(BinOp::Le, 13, 18),
            Inst::Unary(UnOp::Tanh, 30),
            Inst::Extent(0),
            Inst::Binary(BinOp::Eq, 12, 12),
            Inst::Index(0),
            Inst::Index(0),
            Inst::Binary(BinOp::Lt, 9, 33),
            Inst::Extent(0),
            Inst::Const(34.625),
            Inst::Extent(0),
            Inst::Unary(UnOp::Abs, 12),
            Inst::Binary(BinOp::Min, 34, 23),
            Inst::Binary(BinOp::Max, 19, 12),
            Inst::Const(24.6875),
            Inst::Input(1),
            Inst::Const(40.625),
            Inst::Input(0),
            Inst::Unary(UnOp::Abs, 27),
            Inst::Binary(BinOp::Min, 4, 24),
            Inst::Input(0),
            Inst::Unary(UnOp::Floor, 44),
            Inst::Binary(BinOp::Ne, 51, 10),
            Inst::Reduce(RedOp::Min, 51),
            Inst::Unary(UnOp::Tanh, 42),
            Inst::Unary(UnOp::Floor, 18),
            Inst::Extent(0),
            Inst::Select(15, 11, 54),
            Inst::Const(51.1875),
            Inst::Select(53, 56, 13),
            Inst::Binary(BinOp::Le, 54, 29),
            Inst::Binary(BinOp::Min, 39, 37),
            Inst::Binary(BinOp::Add, 48, 60),
        ],
        outputs: vec![(0, 29)],
    }
}
