[package]
name = "qwen3"
edition.workspace = true
license = "MIT OR Apache-2.0"
publish = false
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
all-fusions = []
bf16 = []
default = ["all-fusions"]
final-norm-only = []
qk-norm-rope-only = []
residual-norm-only = []
silu-mul-only = []

[dependencies]
forja-sdk = { path = "../../../crates/forja-sdk" }
