[package]
name = "forja-host"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
forja-core = { path = "../forja-core" }
wasmtime.workspace = true

[dev-dependencies]
forja-cpu = { path = "../forja-cpu" }

[lints]
workspace = true
